id = "nix"
name = "Nix"
description = "Nix support."
version = "0.1.0"
schema_version = 1
authors = ["Hasit Mistry <hasitnm@gmail.com>"]
repository = "https://github.com/zed-extensions/nix"

[grammars.nix]
repository = "https://github.com/nix-community/tree-sitter-nix"
commit = "b3cda619248e7dd0f216088bd152f59ce0bbe488"

[language_servers.nixd]
name = "Nixd"
language = "Nix"
