id = "nix"
name = "Nix"
description = "Nix support."
version = "0.1.4"
schema_version = 1
authors = ["Hasit Mistry <hasitnm@gmail.com>"]
repository = "https://github.com/zed-extensions/nix"

[grammars.nix]
repository = "https://github.com/nix-community/tree-sitter-nix"
commit = "<GRAMMAR_COMMIT_AFTER_MERGE>"

[language_servers.nil]
name = "nil"
language = "Nix"

[language_servers.nixd]
name = "nixd"
language = "Nix"
